### ISSUE TITLE
No longer seems to work on WC 3.1.2 w/ Divi

### ISSUE THREAD

**Issue by ratputin** [jameskoster/woocommerce-product-image-flipper#13]
James,
I doubt this is a bug, probably has more to do with our build than the plugin itself, but I can't sort it. After the last round of updates, the image flipper doesn't respond at all. Is there any chance you'd (or someone you trust) would be willing to offer a fix via a freelance gig? Or point me in the right direction to debug?

The URL is https://itneedstobesaid.com

**Comment by jameskoster** [comment]
I had a look at your markup and the issue seems to be a missing `.woocommerce` class in the DOM above the product list. Adding that should fix the issue. 

It's normally added to the body tag of any WooCommerce page automatically. I'm not sure why that's not happening here. Probably best to speak to the Divi devs about that.

**Comment by ratputin** [comment]
Thanks James! I appreciate your help. Love the plugin and would be happy to send a donation your way. Paypal?

**Comment by jameskoster** [comment]
@ratputin that's very generous - thanks :) My PayPal is james[at]jameskoster.co.uk.
